### ISSUE TITLE
Search for block by time is bugged

### ISSUE THREAD

**Issue by Alex-Werner** [dashevo/insight-ui#1]
Here is the specific case : I'm trying to seek using the block-data function the block : 725048

1) May be we would like to be able to retrieve directly a block by using the search bar
2) Using this feature, and knowing that this block has been mine on the 23 August, I tried to seek it here : http://insight.dashevo.org/insight/blocks-date/2017-08-23

Displayed are from 725080 to 725278. Pressing olderblock gave me back the same data.
Repressing older block did nothing (same URI).
Trying to see on 2017-08-22 gave me block from 724526 to 724725. 

Therefore block from 724725 to 725080 aren't retrievable using insight-ui

**Comment by chaeplin** [comment]
Found that timestamp xxxx not changed.
try http://insight.dashevo.org/insight/blocks-date/2017-08-23/1503512800


by the way, looks like insight use browser time zone and adjusts timestamp oh a block.

* log
2017-08-23 23:53:10 UpdateTip: new best=00000000000003e243aadfbb87d49b815c257ece0fdf303f1d429674bacc88d6  height=725278  log2_work=66.908836  tx=3388997  date=2017-08-23 23:53:05 progress=1.000000  cache=16.6MiB(5292tx)

**Comment by Alex-Werner** [comment]
Indeed, displaying of a block is adjusted. 

When I look for block 725278, it's properly displayed as mined on "Aug 24, 2017 1:53:05 AM". 
Which is what I could expect from a user perspective. 

But this is clearly not good at all 
![image](https://user-images.githubusercontent.com/5849920/29664331-7d78bb26-88cf-11e7-9b60-13e4e0ee33b4.png)

**Comment by gilemon** [comment]
Maybe a way to correct the confusion would be 1) to just display the block_list dates in UTC format?
2) fix the date picking confusion. The Angular UI date-picker is automatically converting the date from 12:00 UTC to browser local time. This is quite confusing as for users who are UTC +X this results in selecting one day in the past (see here https://stackoverflow.com/questions/22623872/angular-ui-datepicker-adjusting-for-timezone)

Check these proposed behaviors here:
https://gilemon.com:3001/insight/blocks-date/2017-10-02

For the date-picker issue it is using AngularJS v1.6.6 so the options ng-model-options="{timezone: 'utc'}" is working, but for the AngularJS version used in this repository, the option can't just work like this. But upgrading AngularJS is different subject...

Let me know if that's helping first as a proof of concept and I'll check if there is a lighter workaround.

**Comment by gilemon** [comment]
Additionally there is an issue with "Older blocks from this date" which take the value from $scope.pagination.moreTs which is equal to the timestamp of the first block. 
If you change it with the value of the latest listed block you can navigate through the day (by 200 increment as specified in insight-api-dash BLOCK_LIMIT).
Again you can check the correction here:
https://gilemon.com:3001/insight/blocks-date/2017-10-02

This can be fixed in insight-ui side adding:

`$scope.pagination.olderBlocks = $scope.pagination.moreTs;
	  for (var key in $scope.blocks)
	  {
		  if($scope.blocks[key].time < $scope.pagination.olderBlocks)  $scope.pagination.olderBlocks = $scope.blocks[key].time;
	  }` 

 in the Blocks.get function BlocksController 
and changing the block_list.html view:

`<a class="btn btn-primary" href="blocks-date/{{pagination.current}}/{{pagination.olderBlocks}}">Older blocks from this date</a>`

**Comment by nmarley** [comment]
Fixed by #15 as shown above.
